# Generated by Django 3.2 on 2022-01-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('Bill_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Bill_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bill_Date', models.DateField()),
                ('Bill_Type', models.CharField(max_length=50)),
                ('Bill_Checked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('Investor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Investor_Email', models.EmailField(max_length=254)),
                ('Investor_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('Invoice_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Invoice_Date', models.DateField()),
                ('Invoice_Status', models.CharField(max_length=50)),
                ('Invoice_Investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashcall.investors')),
                ('List_of_Bills', models.ManyToManyField(to='cashcall.Bills')),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('Investment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Investment_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Investment_Date', models.DateField()),
                ('Investment_Fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Investor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashcall.investors')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='Bill_Investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashcall.investors'),
        ),
    ]
