# Generated by Django 3.2 on 2022-01-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashcall', '0002_auto_20220128_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='Invoice_Status',
            field=models.CharField(choices=[('validated', ''), ('sent', ''), ('paid', ''), ('overdue', '')], default='validated', max_length=50),
        ),
    ]
